import { Hero } from './hero';

export const LIST: Hero[] = [
  { id: 1, name: 'Tracer' },
  { id: 2, name: 'Reaper' },
  { id: 3, name: 'Widowmaker' },
  { id: 4, name: 'Pharah' },
  { id: 5, name: 'Reinhardt' },
  { id: 6, name: 'Mercy' },
  { id: 7, name: 'Torbjörn' },
  { id: 8, name: 'Hanzo' },
  { id: 9, name: 'Winston' },
  { id: 10, name: 'Zenyatta' },
  { id: 11, name: 'Bastion' },
  { id: 12, name: 'Symmetra' },
  { id: 13, name: 'Zarya' },
  { id: 14, name: 'McCree' },
  { id: 15, name: 'Soldier: 76' },
  { id: 16, name: 'Lúcio' },
  { id: 17, name: 'Roadhog' },
  { id: 18, name: 'Junkrat' },
  { id: 19, name: 'D.Va' },
  { id: 20, name: 'Mei' },
  { id: 21, name: 'Genji' },
  { id: 22, name: 'Ana' },
  { id: 23, name: 'Sombra' },
  { id: 24, name: 'Orisa' },
  { id: 25, name: 'Doomfist' },
  { id: 26, name: 'Moira' },
  { id: 27, name: 'Brigitte' },
  { id: 28, name: 'Wrecking Ball' },
  { id: 29, name: 'Ashe' },
  { id: 30, name: 'Baptiste' }
];
